# -*- coding: utf-8 -*-
"""Copy of Iterative_eigenvalues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObsGpU1BuX5JOYG3DQgz25PT7QxArIu6

#**Lab 9 - Iterative eigenvalues and Markov chains**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab9"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="JADEN"

last_name="SEARLE"

# Enter your Math 215 section number in between the quotation marks.

section_number="Your Math 215 section number goes here"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="JADENWS"

"""**Import NumPy**"""

import numpy as np

"""**Problem 1**"""

# This function approximates the dominant eigenvector of our matrix A.

def evect_approx1(x_0,k):
  A = np.array([[1, 1],
                [2, 0]])
  x_k = x_0
  for _ in range(k):
      x_k = np.dot(A, x_k)
  return x_k

print(evect_approx1(np.array([1, 9]),10))

"""**Problem 2**"""

# This function approximates the dominant eigenvalue of our matrix A.

def eval_approx1(x_0,k):
  A = np.array([[1, 1],
                [2, 0]])
  x_k = x_0
  for _ in range(k):
    x_k = np.dot(A, x_k)
  x_next = np.dot(A, x_k)
  eval = x_next[0] / x_k[0]
  return eval

print(eval_approx1(np.array([1, 9]),10))

"""**Problem 3**"""

# This function approximates the dominant eigenvalue and eigenvector of our matrix A using the normalized iterative process.

def norm_evect_approx1(x_0,k):
  A = np.array([[1, 1],
                [2, 0]])
  x_k = x_0
  for _ in range(k):
      x_k_prev = x_k
      w_k = np.dot(A, x_k)
      x_k = w_k / np.linalg.norm(w_k)

  eigenvalue_approx = w_k[0] / x_k_prev[0]
  return x_k, eigenvalue_approx

print(norm_evect_approx1(np.array([1, 9]), 10))

"""**Problem 4**"""

# This function approximates the dominant eigenvalue and eigenvector of an arbitrary matrix using the process described in Problem 4.

def norm_approx_gen(M, x_0, k):
    x_prev = np.array(x_0)
    for i in range(k):
        w = np.dot(M, x_prev)
        max_abs_w = np.max(np.abs(w))
        x_curr = w / max_abs_w
        if i == k - 1:
            x_k_minus_1 = x_prev.copy()
            w_k = w.copy()
        x_prev = x_curr
    lambda_approx = w_k[0] / x_k_minus_1[0]
    return x_prev, lambda_approx

M = np.array([[2, 4, 6], [4, 8, 0], [1, 2, 9]])
x_0 = np.array([1, 5, -1])
iterations = 10
print(norm_approx_gen(M, x_0, iterations))

"""**Problem 5**"""

# This function approximates the dominant eigenvalue and eigenvector of an arbitrary matrix using the Rayleigh quotiend as described in Problem 5.

def ray_quotient(M,x_0,k):
  x_k, _ = norm_approx_gen(M, x_0, k)

  eigenval = np.dot(x_k.T, np.dot(M, x_k)) / np.dot(x_k.T, x_k)

  return eigenval

M = np.array([[2, 4, 6], [4, 8, 0], [1, 2, 9]])
x_0 = np.array([1, 5, -1])
iterations = 10
print(ray_quotient(M, x_0, iterations))

"""**Problem 6**"""

mat = np.array([[3, 2, -2], [-1, 1, 4], [3, 2, -5]])
x_0 = np.array([1, 1, 1])


x_vect_3 = (norm_approx_gen(mat, x_0, 3))[0]
x_vect_4 = (norm_approx_gen(mat, x_0, 4))[0]

print(x_vect_3)
print(x_vect_4)

"""**Problem 7**"""

# This function returns the number of subscribers to the different streaming services after month k.

def subscriber_vals(x_0,k):
  P = np.array([[0.7, 0.2],
                [0.3, 0.8]])
  x_k = x_0
  for _ in range(k):
      # Apply the transition matrix P to the current state x_k
      x_k = np.dot(P, x_k)

  return x_k

# Test case
initial_state = np.array([95, 102])
months = 10
print(subscriber_vals(initial_state, months))

"""**Problem 8**"""

# Replace all of the 0 values with the value requested in Problem 8.
initial_state = np.array([120, 80])
months = 6

subscribers_after_6_months = subscriber_vals(initial_state, months)

netflix_subs6 = subscribers_after_6_months[1] / np.sum(subscribers_after_6_months)
print(netflix_subs6)

"""**Problem 9**"""

# Replace all of the 0 values with the matrix/vector/value requested in Problem 9.

trans_matrix= np.array([
    [0.8, 0.5, 0.3, 0.2],
    [0.05, 0.2, 0.1, 0.1],
    [0.1, 0.1, 0.3, 0.1],
    [0.05, 0.2, 0.3, 0.6]
])

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to [gradescope.com](https://gradescope.com) for grading.
"""