# -*- coding: utf-8 -*-
"""Copy of Intro_to_Python_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtOYp16yaK891_Bvhs-OSCgKpEu7TEr6

# **Lab 2 - Introduction to Python programming II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab2"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="JADEN"

last_name="SEARLE"

# Enter your Math 215 section number in between the quotation marks.

section_number="Your Math 215 section number goes here"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="JADENWS"

"""**Problem 1**"""

my_list=[1,2,3,4]

for i in my_list:
  i=2*i

first_elem=my_list[0]   # Replace the value of 0 with the number described in Problem 1.

"""**Problem 2**"""

def sum_list(L):
  sum = 0
  for i in L:
    sum += i
  return sum

"""**Problem 3**"""

def list_relu(L):
  new_list=L.copy()
  for i in range(len(new_list)):
    if new_list[i] < 0:
      new_list[i] = 0
  return new_list

"""**Problem 4**"""

import numpy as np  # Importing NumPy

my_var=(np.exp(5)-np.log(np.sqrt(5)))/(np.exp(np.cos(3)))

"""**Problem 5**"""

v=np.array([1,3,-2,4,5])
u=np.array([1,1,-2,1,1])
w=np.array([1,0,1,0,1])

my_vect_var=((np.dot(v,u)/np.dot(u,u))*u)+((np.dot(v,w)/np.dot(w,w))*w)

"""**Problem 6**"""

def first_rpt(M):
  new_matrix=M.copy()
  first_row = new_matrix[0,:]
  for i in range(len(M)):
    new_matrix[i,:] = first_row
  return new_matrix

"""**Problem 7**"""

def matrix_sum(M):
  n_rows=len(M)
  n_cols=len(M[0,:])
  sum = 0
  for i in range(n_rows):
    for j in range(n_cols):
      sum += M[i,j]
  return sum

"""**Problem 8**"""

long_list= [0.5**i for i in range(1,101)]

"""**Problem 9**"""

very_long_list= [j**i for i in range(1,100) for j in range(1,4)]

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to [gradescope.com](https://gradescope.com) for grading.
"""